### ISSUE TITLE
Gem::Package::PathError: installing into parent path is not allowed

### ISSUE THREAD

**Issue by groe** [randoum/autonumeric-rails#8] opened 2016-09-27 13:25 UTC
With 1.9.46 I'm getting this error when trying to install the gem:

```
Gem::Package::PathError: installing into parent path /my/path/.rvm/gems/ruby-2.3.1@project/spec of
/my/path/.rvm/gems/ruby-2.3.1@project/gems/autonumeric-rails-1.9.46 is not allowed
An error occurred while installing autonumeric-rails (1.9.46), and Bundler cannot continue.
Make sure that `gem install autonumeric-rails -v '1.9.46'` succeeds before bundling.
```

With 1.9.43 everything works perfectly.

**Comment by randoum** [comment] 2016-09-27 17:36
You need to update rubygems

```
gem install rubygems-update
update_rubygems
```

Feel free to reopen the issue if you need further helping.

**Comment by groe** [comment] 2016-09-28 08:23
Interesting! It worked, thank you.

**Comment by codyrobbins** [comment] 2016-10-18 20:57
Unfortunately this issue currently prevents apps using 1.9.46 from being deployed to Heroku. Apparently Rubygems 2.5.1 has [some sort of bug](https://github.com/AlchemyCMS/alchemy_cms/issues/985) which causes this problem but it has since been fixed in a subsequent release of Rubygems. Unfortunately Heroku is using [Rubygems 2.5.1](https://devcenter.heroku.com/articles/ruby-support#supported-runtimes) for Ruby 2.3.1 and the version of Rubygems used is not configurable.

For anyone else who has this problem, downgrading `autonumeric-rails` to 1.9.43 will allow deployment to Heroku.

**Comment by randoum** [comment] 2016-10-19 05:15
@codyrobbins I have removed the simlink from the spec directory structure. You should not have the bug while deploying on Heroku anymore. Kindly update to 1.9.46.2 and let me know if the problem is solved.

**Closed by randoum** 2016-10-19 05:15 UTC

**Comment by codyrobbins** [comment] 2016-10-19 14:33
@randoum Thanks for the quick response! I just upgrade to 1.9.46.2 and it now deploys on Heroku without any issues. Thanks so much!
